services:
  - type: web
    name: samad-nursing-backend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 3000
